create table users
(
    id        bigint       not null
        constraint users_pkey
            primary key,
    firstname varchar(255) not null,
    lastname  varchar(255) not null,
    password  varchar(255) not null,
    role      varchar(255),
    username  varchar(255) not null
        constraint uk_r43af9ap4edm43mmtq01oddj6
            unique
);



create table accounts
(
    id      bigint generated by default as identity
        constraint accounts_pkey
            primary key,
    balance double precision,
    user_id bigint not null
        constraint uk_e4w4av1wrhanry7t6mxt42nou
            unique
);
